- repository: autowarefoundation/sync-file-templates
  source-dir: sources
  files:
    - source: .github/workflows/pre-commit.yaml
    - source: .github/workflows/pre-commit-optional.yaml
    - source: .github/workflows/semantic-pull-request.yaml
    - source: .github/workflows/spell-check-differential.yaml
    - source: .github/workflows/sync-files.yaml
    - source: .clang-format
    - source: .markdown-link-check.json
    - source: .markdownlint.yaml
    - source: .pre-commit-config-optional.yaml
    - source: .pre-commit-config.yaml
    - source: .prettierignore
    - source: .prettierrc.yaml
    - source: .yamllint.yaml
    - source: CPPLINT.cfg
    - source: setup.cfg

# yq is available in the sync-files workflow.
# caveat: by using yq, the original formatting of the yaml files might be lost (especially line breaks)
- repository: autowarefoundation/autoware_universe
  files:
    - source: .github/workflows/pre-commit-lite.yaml
