name: build-test-tidy-pr

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  make-sure-label-is-present:
    uses: autowarefoundation/autoware-github-actions/.github/workflows/make-sure-label-is-present.yaml@v1
    with:
      label: run:build-and-test-differential

  build-and-test-differential:
    if: ${{ always() }}
    needs:
      - make-sure-label-is-present
    strategy:
      fail-fast: false
      matrix:
        rosdistro: [humble, jazzy]
        include:
          - rosdistro: humble
            container: ghcr.io/autowarefoundation/autoware:universe-dependencies-humble
          - rosdistro: jazzy
            container: ghcr.io/autowarefoundation/autoware:universe-dependencies-jazzy

    uses: ./.github/workflows/build-and-test-differential.yaml
    with:
      rosdistro: ${{ matrix.rosdistro }}
      container: ${{ matrix.container }}
      run-condition: ${{ needs.make-sure-label-is-present.outputs.result == 'true' }}

  clang-tidy-differential:
    if: ${{ always() }}
    needs:
      - make-sure-label-is-present
    uses: ./.github/workflows/clang-tidy-differential.yaml
    with:
      run-condition: ${{ needs.make-sure-label-is-present.outputs.result == 'true' }}
